language: node_js
node_js:
  - 10
branchs:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - npm install
script:
 - npm run lint
 - npm test
 - npm run build
 - npm run dist
after_success:
 - npm run coveralls
